config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "bookings#new"

  post "import", to: "bookings#import"
  get "shows", to: "shows#index"
  post "shows", to: "shows#create"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :performance
  has_many :tickets, dependent: :destroy

  validates :booking_date, presence: true
  validates :channel, inclusion: { in: %w(GUICHET DIGITICK) }
  validates :booking_type, inclusion: { in: ["Abonnement", "Place individuelle"] }
end

app/models/performance.rb
class Performance < ApplicationRecord
  belongs_to :show
  has_many :bookings
  has_many :tickets, through: :bookings

  validates :start_date, presence: true
  validates :end_date, presence: true
  # validates :end_date, comparison: { greater_than: :start_date }
end

app/models/show.rb
class Show < ApplicationRecord
  has_many :performances
  has_many :bookings, through: :performances
  has_many :tickets, through: :bookings

  validates :name, presence: true

  def unique_bookings
    self.id ? self.bookings.uniq : Booking.all
  end

  def unique_tickets
    self.id ? self.tickets : Ticket.all
  end

  def buyers
    self.unique_bookings.map(&:user).uniq
  end

  def users_age
    defined_ages = self.buyers.reject{|buyer| buyer.age.nil? }.map(&:age)
    defined_ages.size == 0 ? "Pas d'âge rempli" : "#{defined_ages.inject(:+) / defined_ages.size} ans"
  end

  def avg_price
    self.unique_tickets.map(&:price).inject(:+).fdiv(self.unique_tickets.size).round(2)
  end
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :booking

  validates :price, numericality: true, presence: true

  enum status: {
    on_sale: 1,
    sold: 2
  }

  # def self.price
  #   Ticket.all.map(&:price).inject(:+).fdiv(Ticket.all.size)
  # end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings
  has_many :tickets, through: :bookings

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :gender, inclusion: { in: ["H", "F"] }, :allow_nil => true
  validates :age, numericality: { only_integer: true }, :allow_nil => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
  end

  def import
    if params[:file].nil?
      raise_alert("Pas de fichier ajouté")
    else
      CsvImport.new(params[:file]).call
    end
  end

  private

  def raise_alert(message)
    flash[:alert] = message
    return redirect_to root_path()
  end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  def index
    @shows = Show.all.map(&:name)
    if params[:search].present?
      @show = Show.find_by(name: params[:search])
      respond_to do |format|
        format.html
        format.text { render partial: "shows/results", locals: { show: @show }, formats: [:html] }
      end
    else
      @show = Show.new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="alert">
  <%= alert %>
</div>
<div class="m-5 text-center">
  <%= form_tag import_path, method: :post, multipart: true do %>
    <%= file_field_tag :file, accept: ".csv" %>
    <%= submit_tag 'Import' %>
  <% end %>
</div>
<div class="m-5 text-center">
  <%= link_to "Statistiques", shows_path(), class: "btn btn-primary" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestArMex</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shows/_results.html.erb
<div class="row m-5 text-center">
  <div class="col-6">
    Nombre de réservations: <%= show.unique_bookings.size %>
  </div>
  <div class="col-6">
    Nombre d'acheteurs uniques: <%= show.buyers.size %>
  </div>
</div>
<div class="row m-5 text-center">
  <div class="col-6">
    Age moyen des acheteurs: <%= show.users_age %>
  </div>
  <div class="col-6">
    Prix moyen par représentation: <%= show.avg_price %> €
  </div>
</div>

app/views/shows/index.html.erb
<div class="container" data-controller="filter-show">
  <div class="row m-5 text-center">
    <%= simple_form_for @show, data: { action:"submit->filter-show#filter" } do |f| %>
      <%= f.input :name, label: false, collection: @shows, input_html: { data: { filter_show_target: "show" } } %>
      <%= f.button :submit, "Filtrer pour un show", class:"btn btn-primary" %>
    <% end %>
  </div>
  <div data-filter-show-target="results">
    <%= render "results", show: @show %>
  </div>
  <div class="mt-5 text-center">
    <%= link_to "Back to import", root_path(), class: "btn btn-secondary" %>
  </div>
</div>